env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 14
rules: 
  no-console: 0
  import/extensions: "off"
  linebreak-style: "off"
  import/prefer-default-export: "off"
    
